project:
  type: website
  output-dir: docs
website:
  title: "notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jinleiphys
format:
  html:
    theme: cosmo
    css: styles.css
    grid:
      body-width: 900px
      margin-width: 300px




