---
format: 
  html:
    page-layout: article
title: "Post-Prior Equivalence in EBU with T-Matrix Form"
author: "Jin Lei"
date: "2024-12-11"
---
For the reaction process $a + A \to b + B^*$, where the projectile $a$ has a two-body structure $b + x$ and $B^*$ represents any possible states between $x$ and $A$, the IAV model provides a method to compute the relative wave function, $\psi_{xA}$, for the $x + A$ system in this three-body process. The interior part of this wave function gives the nonelastic breakup cross sections, while the asymptotic part provides the elastic breakup (EBU) cross section.

The IAV model offers two approaches to compute this relative wave function: the prior form and the post form. In their paper, they prove the post-prior equivalence in the operator form within the Distorted Wave Born Approximation (DWBA).

In the IAV model using the post form, $\psi_{xA}$ is given by:
$$
| \psi_{xA}  \rangle = \frac{1}{E_x + i\epsilon - H_x} \left( \chi_b^{(-)} \left| V_{bx} + U_{bA} - U_{bB} \right| \chi_a^{(+)} \phi_{bx} \right\rangle
$$
where $| \cdot \rangle$ denotes integration without the $r_x$ variable. Here, $V_{bx}$ is the $b-x$ interaction, $U_{bB}$ is the $b-B$ interaction, and $U_{bA}$ is the $b-A$ interaction. The $\chi_a^{(+)}$ and $\chi_b^{(-)}$ are the distorted waves of $a$ and $b$, respectively. The $\phi_{bx}$ is the relative wave function between $b$ and $x$, and $H_x$ is the Hamiltonian of $x$.

The relationship between the transition potentials of the post and prior forms is given by:
$$
\begin{aligned}
V_{post} & = V_{prior} + U_{aA} + V_{bx} - U_{xA} - U_{bB} \\
& = V_{prior} + (U_{aA} + T_{aA}) + (V_{bx} + T_{bx}) - (U_{xA} + T_{xA}) - (U_{bB} + T_{bB})
\end{aligned}
$$

In the prior form of the IAV model, the relative wave function is given by:
$$
\begin{aligned}
| \psi_{xA}  \rangle = \frac{1}{E_x + i\epsilon - H_x} ( \chi_b^{(-)}| V_{prior} | \chi_a^{(+)} \phi_{bx} \rangle + ( \chi_b^{(-)}| \chi_a^{(+)} \phi_{bx} \rangle
\end{aligned}
$$
It is numerically easier to solve the prior form of the IAV model. However, due to the long-ranged nature of the source term, solving the post form of the IAV model is more challenging.


After discussing with Junzhe and consulting Dr. Rimantas Lazauskas, I concluded that the post-prior equivalence in the EBU with the T-matrix form is not valid. I will address this issue using the $S$-matrix derived from the inhomogeneous equations, which has been proven to be equivalent to the T-matrix form.

## $S$-matrix from Inhomogeneous Equations
The key equation of the IAV model is given by:
$$
[E_x - T_x - U_x] \psi^{(+)}_x(\vec{r}_x) = \rho(\vec{r}_x)
$$

In the post-form representation, due to the lack of a natural cutoff on the $r_x$ variable, $\rho(\vec{r}_x)$ behaves as $O(1/r^2)$ for $r_x \to \infty$. This behavior implies that $\rho(\vec{r}_x)$ is not square-integrable, meaning the $S$-matrix is not well-defined. Specifically, in the partial wave basis, the equation can be rewritten as:
$$
\left\{\frac{\hbar^2}{2\mu_x}\left[\frac{d^2}{dr_x^2} - \frac{l_x(l_x+1)}{r_x^2}\right] + E_x - U_x(r_x)\right\} u_\alpha(r_x) = r_x\rho_\alpha(r_x)
$$
where $\alpha$ is the channel index. Generally, the asymptotic behavior of $u_\alpha(r_x)$ is:
$$
u_\alpha(r_x) \to -SH_l^{(+)} \quad \text{as} \quad r_x \to \infty
$$

<!-- However, as pointed out by Rimas, if the source term $r\rho_\alpha(r_x)$ is not compact and behaves as $O(1/r)$, the boundary condition of $u_\alpha(r_x)$ cannot follow the above form. The reason is that the general solution for a second-order differential equation is a linear combination of two independent solutions, $u(r_x) = A(r_x) + A_0(r_x)$, where:
$$
(E + \frac{d^2}{dr^2})A_0(r) = 0
$$
and
$$
A(r) = \int \left(\int (f(r) - E) \, dr\right) \, dr
$$

Here, $A_0(r)$ is the general solution and can have an outgoing wave form. However, the drift term $A(r)$ is asymptotically divergent. Assuming the asymptotic behavior of $f(r)$ is $O(1/r)$, then:
$$
A(r) \to \int \left(\int \left(\frac{1}{r} - E\right) \, dr\right) \, dr \to \int (\ln(r)) \, dr \to r \ln |r| - r
$$

This divergence highlights the challenges in defining the boundary conditions and the $S$-matrix for such systems. -->

<!-- On the other hand,  -->
As Junzhe pointed out, the Hankel function $H_l^{(+)}$ satisfies the following differential equation:
$$
\frac{\mathrm{d}^2 f}{\mathrm{d} x^2} + \left(1 - \frac{2 \eta}{x} - \frac{\lambda(\lambda+1)}{x^2}\right) f(x) = 0
$$
However, if the source term behaves as $O(1/r)$ and we assume the asymptotic behavior of $u_\alpha(r_x) \to -SH^{(+)}_l(r_x)$, then $H^{(+)}_l(r_x)$ will not satisfy the original equation. Instead, the equation becomes:
$$
\frac{\mathrm{d}^2 f}{\mathrm{d} x^2} + \left(1 - \frac{2 \eta}{x} - \frac{\lambda(\lambda+1)}{x^2}\right) f(x) = \frac{1}{x}
$$
This discrepancy indicates that the presence of the $O(1/r)$ source term modifies the differential equation, meaning $H^{(+)}_l(r_x)$ is no longer a valid solution under these conditions. This highlights the need for a different approach to account for the modified source term and its impact on the solution's asymptotic behavior.

## Comments on the Vincent-Fortune Method
The inhomogeneous equation can also be solved using the Green's function method. The radial part of the wave function in the partial wave basis can be expressed as:
$$ 
u_\alpha(r_x) = \int G_\alpha(r_x, r_x') r'_x \rho_\alpha(r_x') \, dr_x'
$$
Since the source term behaves as $O(1/r)$, the Green's function $G_\alpha(r_x, r_x')$ is not square-integrable, leading to divergence of the integral and causing the same issue as the $S$-matrix approach. Vincent and Fortune proposed a method to address this issue by introducing a cutoff in the $r_x$ variable and integrating on the complex plane, making the integration feasible. However, as Junzhe pointed out, this method is not rigorous and may introduce unphysical results.

The Green's function $G_\alpha(r_x, r_x')$ can be written as:
$$
G_\alpha(r_x, r_x') = f_l(r_x<) h_l(r_x>) 
$$
where $f_l$ is the regular solution of the homogeneous equation and $h_l$ is the irregular solution of the homogeneous equation with the boundary condition $H_l^{(+)}$. As Junzhe noted, this solution is only valid when the source term function is compact. In the current case, $h_l$ should be the solution of the equation:
$$
\frac{\mathrm{d}^2 f}{\mathrm{d} x^2} + \left(1 - \frac{2 \eta}{x} - \frac{\lambda(\lambda+1)}{x^2}\right) f(x) = \frac{1}{x}
$$
If one directly uses the Green's function without modifying the irregular solution, the result will be unphysical.
